FROM python:3.13-slim-trixie

# Set Dagster environment variables
ENV DAGSTER_HOME=/opt/dagster/dagster_home/
ENV DAGSTER_APP_DIR=/opt/dagster/app

# Create DAGSTER_HOME and APP code directory
RUN mkdir -p $DAGSTER_HOME $DAGSTER_APP_DIR

# Set working directory
WORKDIR /opt/dagster/app

# Copy dependency files
COPY ./dagster_app $DAGSTER_APP_DIR

# Install dependencies globally
RUN pip install --editable .

# Expose port for dagster-webserver
EXPOSE 3000
ENTRYPOINT ["dg", "dev", "-h", "0.0.0.0", "-p", "3000"]