pipelines:
  - asset_name: cuenca_temp
    sql_query: >
      select date_trunc('hour', md."timestamp") as hour, 
        md.station_id,
        avg(md.temperature ) as avg_temperature,
        md.geom
      from sample_db.public.meteo_data md
      where date_trunc('day', md."timestamp") = '{{partition}}'
      group by hour, md.station_id, md.geom
    prefix_schema: public
    prefix_table: cuenca_temp

  - asset_name: cuenca_hum
    sql_query: >
      select date_trunc('hour', md."timestamp") as hour, 
        md.station_id,
        avg(md.humidity) as avg_humidity,
        md.geom
      from sample_db.public.meteo_data md
      where date_trunc('day', md."timestamp") = '{{partition}}
      group by hour, md.station_id, md.geom
    prefix_schema: public
    prefix_table: cuenca_hum

  - asset_name: cuenca_pres
    sql_query: >
      select date_trunc('hour', md."timestamp") as hour, 
        md.station_id,
        avg(md.pressure) as avg_pressure,
        md.geom
      from sample_db.public.meteo_data md
      where date_trunc('day', md."timestamp") = '{{partition}}'
      group by hour, md.station_id, md.geom
    prefix_schema: public
    prefix_table: cuenca_pres
